import Logo from "./component/Logo"
import Navigation from "./component/Navigation"

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <Logo />
        <Navigation />
      </header>
      <body>{children}</body>
      <footer>CopyRight @ The wild Oasis </footer>
    </html>
  )
}
