import Logo from "./component/Logo"
import Navigation from "./component/Navigation"

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <header>
          <Logo />

        </header>
        <Navigation />
        <main>
          {children}</main>
        <footer>CopyRight @ The wild Oasis </footer>
      </body>

    </html>
  )
}
