import Logo from "@/app/_component/Logo"
import Navigation from "@/app/_component/Navigation"
import "@/app/_styles/globals.css";






export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className="bg-primary-950 text-primary-100 min-h-screen">
        <header>
          <Logo />

        </header>
        <Navigation />
        <main>
          {children}</main>
        <footer>CopyRight @ The wild Oasis </footer>
      </body>

    </html>
  )
}
